# Generated by Django 4.2.5 on 2023-10-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0004_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
